services:
  autosupport:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: autosupport
    env_file:
      - .env
    volumes:
     - type: bind
       source: ./autosupport.db
       target: /usr/src/app/autosupport.db
    command: bun start