version: '3.8'

services:
  autosupport:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: autosupport
    env_file:
      - .env
    command: bun start